#! /bin/bash
java -jar etc/antlr.jar -no-listener -no-visitor -Xexact-output-dir $1 
output_dir=`dirname $1`
basename=`basename $1`
basename=${basename//.g4/}
rm -rf output_dir ${basename}Lexer* ${basename}Parser* ${basename}Listener*
