name: Python & Haskell CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'   # Ignore changes to README.md
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Python dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 parallel z3 cvc4  

    - name: Install GHC and Cabal
      run: |
        sudo apt-get install -y ghc cabal-install
        cabal update

    - name: Install Haskell packages
      run: |
        cabal install testing-feat size-based
        cabal install --lib testing-feat size-based

    - name: Test ET 
      run: |
        bin/gen_tester grammars/Bitvectors.g4
        bin/run_tester 2 100 Bitvectors solvers.cfg
        checksum=$(cat tests/Bitvectors/*.smt2 | md5sum | awk '{print $1}')
        expected_checksum="09afe38ea30ca3ae7eccff6ed176da01"
        [[ "$checksum" != "$expected_checksum" ]] && { echo "Checksum does not match. Exiting."; exit 1; }
        echo "Checksum matches."

