name: Python & Haskell CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Python dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 parallel z3 cvc4  

    - name: Install GHC and Cabal
      run: |
        sudo apt-get install -y ghc cabal-install
        cabal update

    - name: Install Haskell packages
      run: |
        cabal install testing-feat size-based
        cabal install --lib testing-feat size-based

    - name: Test ET 
      run: |
        bin/gen_tester grammars/Bitvectors.g4
        bin/run_tester 2 100 Bitvectors solvers.cfg
        checksum=$(cat tests/Bitvectors/*.smt2 | md5sum | awk '{print $1}')
        echo $checksum
        cat tests/Bitvectors/0.smt2
        #expected_checksum="7a478e799c7e705d8895d92cdce2f067"
        # Exit with 1 if checksum doesn't match
        ls tests/Bitvectors/|wc -l
        #[[ "$checksum" != "$expected_checksum" ]] && { echo "Checksum does not match. Exiting."; exit 1; }
        #echo "Checksum matches."
        
